### PR TITLE
Error when no screen found

### PR DESCRIPTION
**Pull request by AlexisBRENON**

### CODE REVIEW

**Comment by AlexisBRENON** [comment]
@juleswh I tried something with a context manager, which make the things clearer (I feel). Can you try it (I don’t have workstation to test it...) ? Does it work as expected ?

**Comment by juleswh** [comment]
Apparently the upgrade breaks everything.

Apart from that, rolling back to c3929dc, there is only one bug :

- I have 2 screens, north and south;
- I have a maximized window (a terminal emulator);
- I call `move-to-monitor -d EAST` or `move-to-monitor -d WEST`;
- :x: **The window gets _un-maximized_**;
- otherwise it goes as expected (does not change screen, exit with status=1, prints traceback and error)

From the code, I really can't understand why. In situations where the window is moved as expected, there are no problems with the maximization.

**Comment by juleswh** [comment]
I updated my comment. The reported bug is the only new thing.
The other bug I though were due to the upgrade might not be new, it occurs when a window is across two screens.

**Comment by AlexisBRENON** [comment]
Didn’t read the documentation:
> If an unhandled exception occurs in the block, it is reraised inside the generator at the point where the yield occurred. Thus, you can use a `try…except…finally` statement to [...] ensure that some cleanup takes place

Should be better now.

**Comment by juleswh** [comment]
All good now !

**Pull request merged**
